spring:
  application:
    name: member-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRE_TIME}

server:
  port: 8080
  # 修正 Cloud Run Proxy 設定
  forward-headers-strategy: framework

logging:
  level:
    # 防止 Hibernate 輸出連線池詳細資訊的 Log
    org.hibernate.orm.connections.pooling: WARN
